apiVersion: apps/v1
kind: Deployment
metadata:
  name: skmz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skmz
  template:
    metadata:
      labels:
        app: skmz
    spec:
      containers:
        - name: skmz
          image: btthanhk4/skmz:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: skmz-service
spec:
  selector:
    app: skmz
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
